# to tell travis that we need admin privilege
sudo: required
language: generic
# to tell travis which service is required
services:
  - docker
# hooks to tell what need to be done before install
before_install:
# give the command that we want to run.
# -t --> adding a tag for the image that will be generated after the build
# We can give tag any name e.g. test, myimage etc. but its convention to use
# github username/repo name
# this tag then can be referred in the .travis.yml file to refer to the image ID
  - docker build -t myimage -f Dockerfile.dev .
# to tell which commands needs to be run
script:
#              additional variables to be compatible with jest library
  - docker run -e CI=true myimage npm run test